WebOne/WebOne/urls.py
from django.contrib import admin
from django.urls import path
from appOne import views
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),
    path('appOne/',include('appOne.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

WebOne/appOne/urls.py
from django.conf.urls import include
from django.urls import path
from appOne import views

app_name = 'appOne'
urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('add_module/', views.add_module, name='add_module'),
    path('modules/<str:pk>/addchapter/', views.add_chapter, name='add_chapter'),
    path('manage_module/', views.manage_module, name='manage_module'),
    path('modules/<str:pk>/',views.manage_chapter, name='module_home'),
    path('modules/<str:pk>/manage_chapter/',views.manage_chapter, name='manage_chapter'),
    path('modules/<str:pk>/chapters/<str:pq>/',views.manage_question, name='chapter_home'),
    path('modules/<str:pk>/chapters/<str:pq>/manage_question/',views.manage_question, name='manage_question'),
    path('modules/<str:pk>/chapters/<str:pq>/add_question/',views.add_question,name='add_question'),
    path('prof/',views.prof_page, name = 'prof_page'),
    path('student/',views.student_page, name = 'student_page'),
    path('modules/<str:pk>/chapters/<str:pq>/chat/', views.chat, name = 'chat'),
    path('modules/delete_chapter/<module_pk>/<chapter_name>', views.delete_chapter, name="delete_chapter"),
    path('modules/delete_question/<module_pk>/<chapter_name>/<question_name>',views.delete_question, name="delete_question"),
    path('modules/delete_module/<module_pk>/',views.delete_module, name='delete_module'),
    path('modules/<str:pk>/chapters/<str:pq>/publish/', views.publish_chapter, name='publish_chapter'),
    path('<m_name>/<ch_name>/start_quiz/',views.start_question, name='start_question'),
    path('<m_name>/<ch_name>/<int:q_num>/',views.view_question, name='view_question'),
    path('<m_name>/<ch_name>/view_result/', views.view_chapter_result, name='view_result'),
    path('<m_name>/<ch_name>/<int:q_num>/addsolution/',views.add_solution, name='add_solution'),
]
"""
urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('add_module/', views.add_module, name='add_module'),
    path('<str:pk>/addchapter/', views.add_chapter, name='add_chapter'),
    path('manage_module/', views.manage_module, name='manage_module'),
    path('<str:pk>/',views.manage_chapter, name='module_home'),
    path('<str:pk>/manage_chapter/',views.manage_chapter, name='manage_chapter'),
    path('<str:pk>/<str:pq>/',views.manage_question, name='chapter_home'),
    path('<str:pk>/<str:pq>/manage_question/',views.manage_question, name='manage_question'),
    path('<str:pk>/<str:pq>/add_question/',views.add_question,name='add_question'),
    path('prof/',views.prof_page, name = 'prof_page'),
    path('student/',views.student_page, name = 'student_page'),
    path('<str:pk>/<str:pq>/chat/', views.chat, name = 'chat'),
    path('delete_chapter/<module_pk>/<chapter_name>', views.delete_chapter, name="delete_chapter"),
    path('delete_question/<module_pk>/<chapter_name>/<question_name>',views.delete_question, name="delete_question"),
    path('delete_module/<module_pk>/',views.delete_module, name='delete_module'),
    path('<str:pk>/<str:pq>/publish/', views.publish_chapter, name='publish_chapter'),
    path('<m_name>/<ch_name>/start_quiz/',views.start_question, name='start_question'),
    path('<m_name>/<ch_name>/<int:q_num>/',views.view_question, name='view_question'),
] """

WebOne/appOne/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
#import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.utils.timezone import now

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

class AddModuleForm(forms.ModelForm):
    class Meta:
        model = Module
        fields = '__all__'
        labels = {'module_name': 'Name of module'}

class AddChapterForm(forms.ModelForm):
    class Meta:
        model = Chapter
        exclude = ['module', 'can_start', 'end_datetime']
        labels = {'chapter_name': 'Name of chapter',
                    'chapter_desc': 'Description'}

class AddQuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        # fields = '__all__'
        exclude = ['chapter', 'question_number']
        labels = {'question_name' : 'Question statement',
                    'question_optionA': 'Option A',
                    'question_optionB': 'Option B',
                    'question_optionC': 'Option C',
                    'question_optionD': 'Option D' }

class AddSolutionForm(forms.ModelForm):
    class Meta:
        model = Solution
        # fields = '__all__'
        exclude = ['question']
        labels = {'solution_answer': 'Correct Answer',
                    'solution_explanation': 'Explanation'}

class PublishChapterForm(forms.Form):
    end_datetime = forms.DateTimeField(label="Date to end chapter")

    def clean_end_datetime(self):
        data = self.cleaned_data['end_datetime']
        
        # Raise error if the end date is in the past. 
        if data < now():
            raise ValidationError(_('Invalid date - end date in the past'))

        # Return the cleaned data.
        return data

WebOne/appOne/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import *
from .utilities import create_teams

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, Http404
# below is deprecated
#from django.core.urlresolvers import reverse
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required

import firebase_admin
from firebase_admin import auth, credentials, db

cred = credentials.Certificate("../cz3002-firebase-adminsdk-zn2kj-457d20ac3e.json")
firechat_app = firebase_admin.initialize_app(cred, {
    'databaseURL' : 'https://cz3002.firebaseio.com/'
})
room_ref = db.reference('room-metadata')

#make sure you have form name whenever you are dealing with form.
# Create your views here.
@login_required
def index(request):


    return render(request, 'appOne/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in, Nice!")

"""this is decorator, to highlight that user_logout
   happens only user logged in alr"""
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']


            profile.save()
            registered = True
            return HttpResponseRedirect(reverse('index'))
        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'appOne/registration.html',
                    {'user_form':user_form,
                     'profile_form':profile_form,
                     'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)

                if user.groups.filter(name = 'Professors').exists():
                    return HttpResponseRedirect(reverse('appOne:prof_page'))

                elif user.groups.filter(name = 'Students').exists():
                    return HttpResponseRedirect(reverse('appOne:student_page'))

                return HttpResponseRedirect(reverse('index')) #back to home page

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")

        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied!")

    else:
        return render(request,'appOne/login.html',{})

@permission_required('appOne.add_module', raise_exception=True)
def add_module(request):
    if request.method == 'POST':
        form = AddModuleForm(request.POST)

        if form.is_valid():
            module = form.save(commit=False)
            module.save()
            print("Done")
            # return redirect('/appOne/prof')
            return redirect('/appOne/prof')
    else:
        form = AddModuleForm()

    context = {
        'form': form,
    }

    return render(request, 'appOne/addmodule.html', context)

@permission_required('appOne.add_chapter', raise_exception=True)
def add_chapter(request, pk):
    module_stored = get_object_or_404(Module, module_name=pk)
    prof = Professor.objects.get(user=request.user)
    if prof == module_stored.coordinator :
        if request.method == 'POST':
            form = AddChapterForm(request.POST)

            if form.is_valid():
                chapter = form.save(commit=False)
                chapter.module = module_stored
                chapter.save()

                # return HttpResponseRedirect(reverse('index'))
                # return redirect(f'/appOne/modules/{pk}/manage_chapter/')
                return redirect('/appOne/prof')
        else:
            form = AddChapterForm()

        context = {
            'form': form,
            'module': module_stored
        }
        return render(request, 'appOne/addchapter.html', context)
    else:
        raise Http404(u"Access Denied")


@permission_required('appOne.add_question', raise_exception=True)
def add_question(request, pk, pq):
    module_stored = get_object_or_404(Module, module_name=pk)
    prof = Professor.objects.get(user=request.user)
    if prof == module_stored.coordinator :
        chapter_stored = get_object_or_404(Chapter, module = module_stored, chapter_name=pq)
        
        if chapter_stored.can_start:
            raise Http404(u"Already published")
        elif request.method == 'POST':
            form = AddQuestionForm(request.POST)

            if form.is_valid():
                question = form.save(commit=False)
                question.question_number = Question.objects.filter(chapter=chapter_stored).count() + 1
                print(question.question_number)
                question.chapter = chapter_stored
                question.save()
                print(question.pk)
                # return HttpResponseRedirect(reverse('index'))
                return redirect(f'/appOne/modules/{pk}/chapters/{pq}/manage_question/')

        else:
            form = AddQuestionForm()

        context = {
            'form': form,
            'chapter': chapter_stored
        }

        return render(request, 'appOne/addquestion.html', context)
    else:
        raise Http404(u"Access Denied")

@permission_required('appOne.add_solution', raise_exception=True)
def add_solution(request, m_name, ch_name, q_num):
    module_stored = get_object_or_404(Module, module_name=m_name)
    prof = Professor.objects.get(user=request.user)
    if prof == module_stored.coordinator :
        chapter_stored = get_object_or_404(Chapter, module = module_stored, chapter_name=ch_name)
        question_stored = get_object_or_404(Question, chapter=chapter_stored, question_number=q_num)

        if hasattr(question_stored, 'solution'):
            raise Http404(u"Already added solution!")
        elif request.method == 'POST':
            form = AddSolutionForm(request.POST)

            if form.is_valid():
                solution = form.save(commit=False)
                solution.question = question_stored
                solution.save()
                return redirect(f'/appOne/modules/{m_name}/chapters/{ch_name}/manage_question/')

        else:
            form = AddSolutionForm()

        context = {
            'form': form,
            'question': question_stored
        }

        return render(request, 'appOne/addsolution.html', context)
    else:
        raise Http404(u"Access Denied")

@permission_required('appOne.delete_module', raise_exception=True)
def delete_module(request, module_pk):
    module_stored = Module.objects.get(module_name=module_pk)
    prof = Professor.objects.get(user=request.user)
    if prof == module_stored.coordinator :
        module_stored.delete()

        return redirect('/appOne/prof/')
    else:
        raise Http404(u"Access Denied")


@permission_required('appOne.delete_chapter', raise_exception=True)
def delete_chapter(request, module_pk, chapter_name):
    print(module_pk)
    print(chapter_name)

    module_stored = get_object_or_404(Module, module_name=module_pk)
    prof = Professor.objects.get(user=request.user)
    if prof == module_stored.coordinator :
        chapter_stored = Chapter.objects.get(module=module_stored, chapter_name=chapter_name)

        print(chapter_stored)
        chapter_stored.delete()
        # return render(request, 'appOne/delete_chapter.html')
        # return redirect(f'/appOne/modules/{module_pk}/manage_chapter/')
        return redirect('/appOne/prof/')
    else:
        raise Http404(u"Access Denied")

@permission_required('appOne.delete_question', raise_exception=True)
def delete_question(request, module_pk, chapter_name, question_name):
    print(module_pk)
    print(chapter_name)

    module_stored = get_object_or_404(Module, module_name=module_pk)
    prof = Professor.objects.get(user=request.user)
    if prof == module_stored.coordinator :
        chapter_stored = get_object_or_404(Chapter, chapter_name=chapter_name)
        question_stored = Question.objects.get(question_name=question_name)
        question_stored.delete()

        return redirect(f'/appOne/modules/{module_pk}/chapters/{chapter_name}/manage_question/')
    else:
        raise Http404(u"Access Denied")

@permission_required('appOne.change_module', raise_exception=True)
def manage_module(request):

    module_list = Module.objects.filter()
    return render(request,'appOne/manage_module.html',{'module_list':module_list})

@permission_required('appOne.change_chapter', raise_exception=True)
def manage_chapter(request, pk):
    module_stored = get_object_or_404(Module, module_name=pk)
    chapter_list = Chapter.objects.filter(module=module_stored)
    return render(request,'appOne/manage_chapter.html',{'module_pk': pk})

@permission_required('appOne.change_question', raise_exception=True)
def manage_question(request, pk, pq):
    module_stored = get_object_or_404(Module, module_name=pk)
    chapter_stored = get_object_or_404(Chapter, module=module_stored, chapter_name=pq)
    question_list = Question.objects.filter(chapter=chapter_stored)
    context = {
        'module_pk': pk, 
        'chapter_name': pq, 

WebOne/templates/appOne/addmodule.html
{% extends "appOne/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
        <h1>Add module</h1>
        <h3>Details about the new module.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" name="" value="Add Module">
        </form>

    </div>

  </div>

{% endblock %}

WebOne/templates/appOne/base.html
<!DOCTYPE html>
<html>
  <head>
    {% block head_block %}
    {% endblock %}

  </head>
  <body>

    <!-- Original One
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          {# Django Home Link/ Admin Link/ Register Link #}
          <li><a class="navbar-brand" href="{% url 'index' %}">LEONARDISONE</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>

          {# Some logic on what to display for last item #}
          {% if user.is_authenticated%}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'appOne:user_login'%}">Login</a></li>

            {% endif %} -->
            {% block nav_bar %}
          {% endblock %}
        <!--</ul>
      </div>
    </nav> -->


    {% block body_block %}
    {% endblock %}


  </body>
</html>

WebOne/templates/appOne/chat.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />

    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

    <!-- Firebase -->
    <script src="https://www.gstatic.com/firebasejs/3.3.0/firebase.js"></script>

    <!-- Firechat -->
    <link rel="stylesheet" href="https://cdn.firebase.com/libs/firechat/3.0.1/firechat.min.css" />
    <script src="https://cdn.firebase.com/libs/firechat/3.0.1/firechat.min.js"></script>

    <!-- Custom CSS -->
    <style>
      /* Button used to open the chat form - fixed at the bottom of the page */
      .open-button {
        background-color: #555;
        color: white;
        padding: 16px 20px;
        border: none;
        cursor: pointer;
        opacity: 0.8;
        position: fixed;
        bottom: 23px;
        right: 28px;
        width: 280px;
      }
      #firechat-wrapper {
        display: none;
        height: 475px;
        max-width: 325px;
        padding: 10px;
        border: 1px solid #ccc;
        background-color: #fff;
        margin: 50px auto;
        text-align: center;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
        -webkit-box-shadow: 0 5px 25px #666;
        -moz-box-shadow: 0 5px 25px #666;
        box-shadow: 0 5px 25px #666;
        position: fixed;
        bottom: 23px;
        right: 28px;
        width: 280px;
      }
    </style>
  </head>

  <!--
    Example: Anonymous Authentication

    This example uses Firebase Simple Login to create "anonymous" user sessions in Firebase,
    meaning that user credentials are not required, though a user has a valid Firebase
    authentication token and security rules still apply.

    Requirements: in order to use this example with your own Firebase, you'll need to do the following:
      1. Apply the security rules at https://github.com/firebase/firechat/blob/master/rules.json
      2. Enable the "Anonymous" authentication provider in Forge
      3. Update the URL below to reference your Firebase
      4. Update the room id for auto-entry with a public room you have created
   -->
  <body>
    <button class="open-button" onclick="openForm()">Chat</button>
    <div id="firechat-wrapper"></div>
    <script type="text/javascript">
      function openForm() {
        document.getElementById("firechat-wrapper").style.display = "block";
      }
      // Initialize Firebase SDK
      var firebaseConfig = {
                apiKey: "AIzaSyC1SSbgF0CK-SaJ7wbbCMZho2UGaAA2qR0",
                authDomain: "cz3002.firebaseapp.com",
                databaseURL: "https://cz3002.firebaseio.com"
            };
            // Initialize Firebase
            firebase.initializeApp(firebaseConfig);

            firebase.auth().signInWithCustomToken("{{ custom_token }}").catch(function(error) {
              console.log("Error authenticating user:", error);
            });

      // Get a reference to the Firebase Realtime Database
      var chatRef = firebase.database().ref();

      // Create an instance of Firechat
      var chat = new FirechatUI(chatRef, document.getElementById("firechat-wrapper"));

      // Listen for authentication state changes
      firebase.auth().onAuthStateChanged(function(user) {
        if (user) {
          // If the user is logged in, set them as the Firechat user
          chat.setUser(user.uid, user.uid);
          setTimeout(function() {
            chat._chat.enterRoom("{{ room_id }}")
          }, 500);
        } else {
          // If the user is not logged in, sign them in anonymously
          firebase.auth().signInAnonymously().catch(function(error) {
            console.log("Error signing user in anonymously:", error);
          });
        }
      });
    </script>
  </body>
</html>

WebOne/templates/appOne/index.html
{% extends "appOne/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h1>WELCOME TO LEONARDISONE!</h1>
    {% if user.is_authenticated %}
      <h2>WELCOME {{ user.username}}!</h2>
    {% else %}
      <h2>Please Login to LEONARDISONE</h2>
    {% endif %}
  </div>
</div>

{% endblock %}

WebOne/templates/appOne/manage_chapter.html
{% extends "appOne/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
        <h1>List of Chapters</h1>
          {% for chapter in chapter_list %}
              <h3>{{chapter.chapter_name}}</h3>
          {% endfor %}
    </div>
  </div>
{% endblock %}

WebOne/templates/appOne/manage_question.html
{% extends "appOne/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
        <h1>List of Questions</h1>
          {% for question in question_list %}
              <h3>{{question.question_name}}
                <a href="{% url 'appOne:add_solution' m_name=module_pk ch_name=chapter_name q_num=question.question_number %}">Add Solution</a>
                <a href="{% url 'appOne:delete_question' question_name=question.question_name chapter_name=chapter_name module_pk=module_pk %}">Delete</a></h3>
          {% endfor %}
          
          {% if chapter.can_start is False %}
            <a href="{% url 'appOne:add_question' pk=module_pk pq=chapter_name %}">Add Question </a>
            <br>
            <a href="{% url 'appOne:publish_chapter' pk=module_pk pq=chapter_name %}">Publish chapter!</a>
          {% endif %}
    </div>
  </div>
{% endblock %}

WebOne/templates/appOne/publish.html
{% extends "appOne/base.html" %}
{% load staticfiles %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
        <h1>Publish chapter: {{ chapter.chapter_name }}</h1>
        <h3>Allow students to start trying the questions.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <input type="submit" name="" value="Publish Chapter">
        </form>

    </div>

  </div>

{% endblock %}

WebOne/templates/appOne/quiz.html
<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8" />

        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
        <!-- jQuery -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

        <!-- Firebase -->
        <script src="https://www.gstatic.com/firebasejs/3.3.0/firebase.js"></script>

        <!-- Firechat -->
        <link rel="stylesheet" href="https://cdn.firebase.com/libs/firechat/3.0.1/firechat.min.css" />
        <script src="https://cdn.firebase.com/libs/firechat/3.0.1/firechat.min.js"></script>
    <style>
      /* Button used to open the chat form - fixed at the bottom of the page */
      .open-button {
        background-color: #555;
        color: white;
        padding: 16px 20px;
        border: none;
        cursor: pointer;
        opacity: 0.8;
        position: fixed;
        bottom: 23px;
        right: 28px;
        width: 280px;
      }
      #firechat-wrapper {
        display: none;
        height: 475px;
        max-width: 325px;
        padding: 10px;
        border: 1px solid #ccc;
        background-color: #fff;
        margin: 50px auto;
        text-align: center;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        border-radius: 4px;
        -webkit-box-shadow: 0 5px 25px #666;
        -moz-box-shadow: 0 5px 25px #666;
        box-shadow: 0 5px 25px #666;
        position: fixed;
        bottom: 23px;
        right: 28px;
        width: 280px;
      }
        .optBtn{
            height: 100px;
            width: 500px;
            border: 1px black solid;
            padding: 10px 60px;
            margin: 10px;
            font-size: 17px;
            box-shadow: 1px 1px 1px 1px black;
            border-radius:50px;
        }
        .qns{
            list-style-type: none;
            text-align: center;
            border: none;
            width:500px;
            margin:auto;
        }

        .questionNo{
            font-size: 100px;
            color:black;
        }
        .question{
            font-size: 20px;
            vertical-align: top;
            line-height:100px;
        }
        p{
            margin: 10px;
        }
        .option{
            text-align: center;
            margin: auto;
        }
        body{
            background-color: dimgray;
        }
        hr{
            border-top:1px solid rgba(1,1,1,1);
            margin-top: 1rem;
            margin-bottom: 1rem;
            box-shadow: 0.5px 0.5px 0.5px 1px black;
        }
        .back{
            background-color:dimgray;
            height: 50px;
            width: 50px;
            font-size: 40px;
            text-align: center;
            margin:0px;
            line-height: 1px;
        }

        </style>

    </head>
    <body>
    <button class="open-button" onclick="openForm()">Chat</button>
    <div id="firechat-wrapper"></div>
    <button class="back" onclick="goBack()"><</button>

        <script>
        function goBack() {
        window.history.back();
        }
        </script>
    <form method="POST" action="">
      {% csrf_token %}
        <div class="box">
        <div class = "qns">
            <hr>
            <div class="questionNo" name="questionNo">
          {% if haveQuestion %}
            <p>1<span class="question"> {{display_str}} </span></p>


            </div>
            <hr>
            </div>
        <div class="option">
            <input type="submit" class="optBtn" id="option1" value="A" name ="ans_return" onclick = "getAnswer(this.value)" style="background-color: orange">
            <input type="submit" class="optBtn" id="option2" value ="B" name ="ans_return" onclick = "getAnswer(this.value)" style="background-color:skyblue">
            <input type="submit" class="optBtn" id="option3" value ="C" name ="ans_return" onclick = "getAnswer(this.value)" style="background-color:greenyellow">
            <input type="submit" class="optBtn" id="option4" value ="D" name ="ans_return" onclick = "getAnswer(this.value)" style="background-color:orangered">
        </div>
        {% else %}

          <h2> {{optionStr}}: {{display_str}} </h2>
        {% endif %}
        </div>
    </form>
    </body>
    <script>
        function getAnswer(value){
           var answer = value;
            alert("Answer Submitted Successfully");
            console.log(answer);
//            get answer from here to pass to database

        }

        function openForm() {
          document.getElementById("firechat-wrapper").style.display = "block";
        }
        // Initialize Firebase SDK
        var firebaseConfig = {
                  apiKey: "AIzaSyC1SSbgF0CK-SaJ7wbbCMZho2UGaAA2qR0",
                  authDomain: "cz3002.firebaseapp.com",
                  databaseURL: "https://cz3002.firebaseio.com"
              };
              // Initialize Firebase
              firebase.initializeApp(firebaseConfig);

              firebase.auth().signInWithCustomToken("{{ custom_token }}").catch(function(error) {
                console.log("Error authenticating user:", error);
              });

        // Get a reference to the Firebase Realtime Database
        var chatRef = firebase.database().ref();

        // Create an instance of Firechat
        var chat = new FirechatUI(chatRef, document.getElementById("firechat-wrapper"));

        // Listen for authentication state changes
        firebase.auth().onAuthStateChanged(function(user) {
          if (user) {
            // If the user is logged in, set them as the Firechat user
            chat.setUser(user.uid, user.uid);
            setTimeout(function() {
              chat._chat.enterRoom("{{ room_id }}")
            }, 500);
          } else {
            // If the user is not logged in, sign them in anonymously
            firebase.auth().signInAnonymously().catch(function(error) {
              console.log("Error signing user in anonymously:", error);
            });
          }
        });

    </script>
</html>

WebOne/templates/appOne/quiz_results.html
{% extends "appOne/base.html" %}
{% load staticfiles %}

<!-- {% block nav_bar %}
{% endblock %} -->

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <h1>Resuls for Chapter: {{ score }}/{{ total_tried }} ({{ percent_score }}%)</h1>
        {% for qn_sol in qn_sol_list %}
            <h2>{{ qn_sol.0.question_number }}. {{ qn_sol.0.question_name }} ({{ qn_sol.2 }})</h2>
            <h3>{{ qn_sol.1.solution_answer }}</h3>
            <h3>{{ qn_sol.1.solution_explanation }}</h3>
        {% endfor %}
    </div>
  </div>
{% endblock %}